macro(create_project_source_tree TARGET)
    if(MSVC)
        set(PREFIXES ${CMAKE_CURRENT_SOURCE_DIR} ${ARGN} ${NOXPT_SOURCE_DIR})
        get_target_property(SOURCE_LIST ${TARGET} SOURCES)
        foreach(SOURCE_FILE ${SOURCE_LIST})
            if(NOT ${SOURCE_FILE} MATCHES "\<*\>")
                string(TOLOWER ${SOURCE_FILE} SOURCE_FILE_RELATIVE)
                foreach(PREFIX ${PREFIXES})
                    if(SOURCE_FILE_RELATIVE)
                        string(TOLOWER ${PREFIX} PREFIX)
                        string(REPLACE "${PREFIX}" "" SOURCE_FILE_RELATIVE ${SOURCE_FILE_RELATIVE})
                    endif()
                endforeach()

                get_filename_component(SOURCE_PATH_RELATIVE ${SOURCE_FILE_RELATIVE} PATH)
                if(SOURCE_PATH_RELATIVE)
                    string(REPLACE "/" "\\" SOURCE_PATH_RELATIVE ${SOURCE_PATH_RELATIVE})
                endif()
                source_group("${SOURCE_PATH_RELATIVE}" FILES ${SOURCE_FILE})
            endif()
        endforeach()
    endif()
endmacro()
